# Generated by Django 5.0.2 on 2024-03-07 16:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_choice_members'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmedGigs',
            fields=[
                ('venue', models.CharField(max_length=100)),
                ('fee', models.CharField(blank=True, max_length=10, null=True)),
                ('set_type', models.CharField(blank=True, max_length=50, null=True)),
                ('members', models.TextField(blank=True, max_length=20, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
