# Generated by Django 5.0.2 on 2024-03-08 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_nametag_choice_vote_ratio_confirmedgigs_gig_vote_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmedgigs',
            name='tags',
            field=models.ManyToManyField(blank=True, to='polls.nametag'),
        ),
    ]
