# Generated by Django 5.0.2 on 2024-03-08 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_confirmedgigs_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confirmedgigs',
            name='members',
        ),
    ]
