# Generated by Django 5.0.2 on 2024-03-08 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_remove_confirmedgigs_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmedgigs',
            name='additional_info',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
