# Generated by Django 5.0.2 on 2024-03-08 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_remove_choice_members_remove_choice_tags_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ConfirmedGigs',
            new_name='ConfirmedGig',
        ),
    ]
