# Generated by Django 5.0.2 on 2024-03-08 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_rename_confirmedgigs_confirmedgig'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ConfirmedGig',
            new_name='ConfirmedGigs',
        ),
    ]
