# Generated by Django 5.0.2 on 2024-03-10 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_alter_question_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='pub_date',
        ),
    ]
