# Generated by Django 5.0.2 on 2024-03-10 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_remove_choice_choice_text_choice_choice_maybe_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='choice_maybe',
        ),
    ]
