# Generated by Django 5.0.2 on 2024-03-10 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_remove_choice_choice_maybe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='choice_nay',
            new_name='choice_text',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='choice_yay',
        ),
    ]
