# Generated by Django 5.0.2 on 2024-03-11 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0020_alter_choice_choice_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmedgigs',
            name='additional_info',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
