# Generated by Django 5.0.2 on 2024-03-11 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0022_alter_confirmedgigs_additional_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmedgigs',
            name='request',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='confirmedgigs',
            name='venue',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
