# Generated by Django 5.0.2 on 2024-03-11 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0025_alter_confirmedgigs_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmedgigs',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.question'),
        ),
    ]
