# Generated by Django 5.0.2 on 2024-03-14 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0028_alter_vote_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='timestamp',
        ),
    ]
