# Generated by Django 5.0.2 on 2024-03-15 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0029_remove_vote_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='vote_ratio',
        ),
        migrations.AddField(
            model_name='nametag',
            name='vote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.vote'),
        ),
    ]
