# Generated by Django 5.0.2 on 2024-03-17 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0034_remove_vote_tags_remove_confirmedgigs_tags_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confirmedgigs',
            name='tags',
        ),
        migrations.AddField(
            model_name='confirmedgigs',
            name='tags',
            field=models.ManyToManyField(blank=True, to='polls.nametag'),
        ),
    ]
