# Generated by Django 5.0.2 on 2024-03-17 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0036_choice_voter_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='voter_tag',
        ),
        migrations.AddField(
            model_name='question',
            name='voter_tag',
            field=models.ManyToManyField(blank=True, to='polls.nametag'),
        ),
    ]
