# Generated by Django 5.0.2 on 2024-03-18 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0039_remove_confirmedgigs_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmedgigs',
            name='tags',
            field=models.ManyToManyField(blank=True, to='polls.nametag'),
        ),
    ]
