# Generated by Django 5.0.2 on 2024-03-19 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0041_remove_confirmedgigs_tags_confirmedgigs_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confirmedgigs',
            name='name',
        ),
        migrations.AddField(
            model_name='confirmedgigs',
            name='tags',
            field=models.ManyToManyField(blank=True, to='polls.nametag'),
        ),
    ]
