# Generated by Django 5.0.2 on 2024-03-19 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0042_remove_confirmedgigs_name_confirmedgigs_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confirmedgigs',
            name='tags',
        ),
        migrations.AddField(
            model_name='choice',
            name='tags',
            field=models.ManyToManyField(blank=True, to='polls.nametag'),
        ),
    ]
