# Generated by Django 5.0.2 on 2024-03-19 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0046_remove_question_tags_question_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='nametag',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.question'),
        ),
    ]
