# Generated by Django 5.0.2 on 2024-03-23 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0051_remove_confirmedgigs_tags_confirmedgigs_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='tags',
        ),
        migrations.AlterField(
            model_name='choice',
            name='choice_text',
            field=models.CharField(blank=True, choices=[('YAY', 'Yay'), ('NAY', 'Nay')], max_length=200, null=True),
        ),
    ]
