# Generated by Django 5.0.2 on 2024-03-25 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0053_alter_choice_choice_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmedgigs',
            name='confirmed',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
